---
title: "tesk1"
format: html
editor: visual
---

### **Find derivatives using R**

```{r}
library(palmerpenguins)
library(tidyverse)
```

```{r}
my_expression <- expression(x^2)
```

```{r}
my_derivative <- D(expr = my_expression, name = "x")
my_derivative
```

```{r}
x <- 3
```

```{r}
eval(my_derivative)
```

```{r}
#Find the slope
my_expression <- expression(2 * (3 * a + 2)^4 - 5)
my_derivative <- D(expr = my_expression, name = "a")
a = 1.2
my_derivative
eval(my_derivative)
```

```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  geom_point() +
  labs(title = "Penguin bill sizes by species", 
       x = "Bill Length (mm)",
       y = "Bill Depth (mm)")
```

## **Make another penguin plot**

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species)) +
  labs(x = "species",
       y = "Flipper length (mm)",
       title = "Flipper lenght by species",
       subtitle = "Palmer Archipelago, Antarctice (2007 - 2009)",
       caption = "Collected by Dr. Kristen Gorman and colleagues at Palmer Station LTER")
```
